const DEFAULT_BOOKS = [
  {
    "no": "book 0",
    "title": "A-Z English-Hindi Focus Vocabulary Lexicon",
    "author": "Oxford Focus Lexicon",
    "language": "ENG / HIN",
    "status": "READING",
    "start_date": "2026-09-08",
    "end_date": "",
    "count_days": 1,
    "rating": "5",
    "category": "Vocabulary & Language",
    "takeaway": "Real 3D Interactive Flipping Pages Dictionary with English words, Hindi meanings, pronunciations, audio speech, and examples.",
    "availability": "AVAILABLE",
    "isDictionary": true,
    "price": 0,
    "cover_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80"
  },
  {
    "no": "book 1",
    "title": "Hyperfocus",
    "author": "Chris Bailey",
    "language": "HINDI",
    "status": "READING",
    "start_date": "2026-08-21",
    "end_date": "2026-09-06",
    "count_days": 16,
    "rating": "5",
    "category": "Focus & Concentration",
    "takeaway": "कम प्रयास में अधिक सफलता कैसे प्राप्त करें। ध्यान की उत्पादकता: हायपरफ़ोकस (एक काम पर गहरा ध्यान) और स्कैटरफ़ोकस (क्रिएटिव सोच और रिचार्ज)।",
    "availability": "AVAILABLE",
    "price": 350,
    "isbn": "978-93-5543-300-8",
    "cover_image": "hyperfocus_cover.jpg",
    "back_cover": "hyperfocus_back.jpg",
    "total_pages": 240,
    "current_page": 4,
    "cover_url": "https://covers.openlibrary.org/b/id/10239359-M.jpg"
  },
  {
    "no": "book 2",
    "title": "The Power Of Your Subconscious Mind",
    "author": "Joseph Murphy",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/6553019-M.jpg"
  },
  {
    "no": "book 3",
    "title": "Limitless: Upgrade Your Brain, Learn Anything Faster, and Unlock Your Exceptional Life",
    "author": "Jim Kwik",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9360116-M.jpg"
  },
  {
    "no": "book 4",
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13290711-M.jpg"
  },
  {
    "no": "book 5",
    "title": "Deep Work",
    "author": "Cal Newport",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": "",
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7988607-M.jpg"
  },
  {
    "no": "book 6",
    "title": "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    "author": "James Clear",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12539702-M.jpg"
  },
  {
    "no": "book 7",
    "title": "Make It Stick: The Science of Successful Learning",
    "author": "Peter C. Brown",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8188891-M.jpg"
  },
  {
    "no": "book 8",
    "title": "Moonwalking with Einstein: The Art and Science of Remembering Everything",
    "author": "Joshua Foer",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/14426425-M.jpg"
  },
  {
    "no": "book 9",
    "title": "Mindset: The New Psychology of Success",
    "author": "Carol S. Dweck",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/746414-M.jpg"
  },
  {
    "no": "book 10",
    "title": "The Power of Habit: Why We Do What We Do in Life and Business",
    "author": "Charles Duhigg",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9078085-M.jpg"
  },
  {
    "no": "book 11",
    "title": "Brain Rules: 12 Principles for Surviving and Thriving at Work, Home, and School",
    "author": "John Medina",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/2732975-M.jpg"
  },
  {
    "no": "book 12",
    "title": "Focus: the hidden driver of excellence",
    "author": "Daniel Goleman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10398270-M.jpg"
  },
  {
    "no": "book 13",
    "title": "Flow",
    "author": "Mihaly Csikszentmihalyi",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/11041932-M.jpg"
  },
  {
    "no": "book 14",
    "title": "The Organized Mind",
    "author": "Daniel J. Levitin",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7309773-M.jpg"
  },
  {
    "no": "book 15",
    "title": "Your Memory",
    "author": "Kenneth L. Higbee",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/813347-M.jpg"
  },
  {
    "no": "book 16",
    "title": "Peak",
    "author": "Anders Ericsson",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10467082-M.jpg"
  },
  {
    "no": "book 17",
    "title": "The Shallows",
    "author": "Nicholas Carr",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/6458532-M.jpg"
  },
  {
    "no": "book 18",
    "title": "Essentialism",
    "author": "Greg McKeown",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7285986-M.jpg"
  },
  {
    "no": "book 19",
    "title": "Indistractable",
    "author": "Nir Eyal",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9129784-M.jpg"
  },
  {
    "no": "book 20",
    "title": "Spark",
    "author": "John J. Ratey",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/2379210-M.jpg"
  },
  {
    "no": "book 21",
    "title": "A Mind for Numbers",
    "author": "Barbara Oakley",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8352403-M.jpg"
  },
  {
    "no": "book 22",
    "title": "Unlimited Memory",
    "author": "Kevin Horsley",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10102079-M.jpg"
  },
  {
    "no": "book 23",
    "title": "The Brain That Changes Itself",
    "author": "Norman Doidge",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/1333251-M.jpg"
  },
  {
    "no": "book 24",
    "title": "Outliers",
    "author": "Malcolm Gladwell",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10021591-M.jpg"
  },
  {
    "no": "book 25",
    "title": "Grit",
    "author": "Angela Duckworth",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7438753-M.jpg"
  },
  {
    "no": "book 26",
    "title": "Stolen Focus",
    "author": "Johann Hari",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12664855-M.jpg"
  },
  {
    "no": "book 27",
    "title": "Digital Minimalism",
    "author": "Cal Newport",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8507540-M.jpg"
  },
  {
    "no": "book 28",
    "title": "The Art of Learning",
    "author": "Josh Waitzkin",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/475008-M.jpg"
  },
  {
    "no": "book 29",
    "title": "Mastery",
    "author": "Robert Greene",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7561012-M.jpg"
  },
  {
    "no": "book 30",
    "title": "Blink",
    "author": "Malcolm Gladwell",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/14421850-M.jpg"
  },
  {
    "no": "book 31",
    "title": "Predictably Irrational",
    "author": "Dan Ariely",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/2314080-M.jpg"
  },
  {
    "no": "book 32",
    "title": "Drive",
    "author": "Daniel H. Pink",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/6404786-M.jpg"
  },
  {
    "no": "book 33",
    "title": "Mind Mapping",
    "author": "Tony Buzan",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/3876254-M.jpg"
  },
  {
    "no": "book 34",
    "title": "The 5 Second Rule",
    "author": "Mel Robbins",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8114155-M.jpg"
  },
  {
    "no": "book 35",
    "title": "How We Learn",
    "author": "Benedict Carey",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8027675-M.jpg"
  },
  {
    "no": "book 36",
    "title": "The Talent Code",
    "author": "Daniel Coyle",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/11948223-M.jpg"
  },
  {
    "no": "book 37",
    "title": "Pragmatic Thinking and Learning",
    "author": "Andy Hunt",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/5547404-M.jpg"
  },
  {
    "no": "book 38",
    "title": "Rewire Your Brain",
    "author": "John B. Arden",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/6412844-M.jpg"
  },
  {
    "no": "book 39",
    "title": "Memory Rescue",
    "author": "Daniel G. Amen",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12529325-M.jpg"
  },
  {
    "no": "book 40",
    "title": "Switch",
    "author": "Chip Heath and Dan Heath",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/6968365-M.jpg"
  },
  {
    "no": "book 41",
    "title": "Algorithms to Live By",
    "author": "Brian Christian",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8042539-M.jpg"
  },
  {
    "no": "book 42",
    "title": "Thinking in Systems",
    "author": "Donella Meadows",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/14420637-M.jpg"
  },
  {
    "no": "book 43",
    "title": "The Willpower Instinct",
    "author": "Kelly McGonigal",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9475786-M.jpg"
  },
  {
    "no": "book 44",
    "title": "Influence",
    "author": "Robert B. Cialdini",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/431011-M.jpg"
  },
  {
    "no": "book 45",
    "title": "Nudge",
    "author": "Richard H. Thaler",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/6402116-M.jpg"
  },
  {
    "no": "book 46",
    "title": "Mindfulness in Plain English",
    "author": "Henepola Gunaratana",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/4003663-M.jpg"
  },
  {
    "no": "book 47",
    "title": "Waking Up",
    "author": "Sam Harris",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7311247-M.jpg"
  },
  {
    "no": "book 48",
    "title": "10% Happier",
    "author": "Dan Harris",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7277740-M.jpg"
  },
  {
    "no": "book 49",
    "title": "The Power of Now",
    "author": "Eckhart Tolle",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/551262-M.jpg"
  },
  {
    "no": "book 50",
    "title": "Awaken the Giant Within",
    "author": "Anthony Robbins",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/4002352-M.jpg"
  },
  {
    "no": "book 51",
    "title": "The 7 Habits of Highly Effective People",
    "author": "Stephen R. Covey",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10079937-M.jpg"
  },
  {
    "no": "book 52",
    "title": "Smarter Faster Better",
    "author": "Charles Duhigg",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12690321-M.jpg"
  },
  {
    "no": "book 53",
    "title": "Ego is the Enemy",
    "author": "Ryan Holiday",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12447129-M.jpg"
  },
  {
    "no": "book 54",
    "title": "Obstacle is the Way",
    "author": "Ryan Holiday",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/14428233-M.jpg"
  },
  {
    "no": "book 55",
    "title": "Daily Stoic",
    "author": "Ryan Holiday",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13098570-M.jpg"
  },
  {
    "no": "book 56",
    "title": "Principles",
    "author": "Ray Dalio",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8315355-M.jpg"
  },
  {
    "no": "book 57",
    "title": "Think and Grow Rich",
    "author": "Napoleon Hill",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/14542536-M.jpg"
  },
  {
    "no": "book 58",
    "title": "The Miracle Morning",
    "author": "Hal Elrod",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8539416-M.jpg"
  },
  {
    "no": "book 59",
    "title": "Quiet",
    "author": "Susan Cain",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7079753-M.jpg"
  },
  {
    "no": "book 60",
    "title": "Factfulness",
    "author": "Hans Rosling",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8186237-M.jpg"
  },
  {
    "no": "book 61",
    "title": "Range",
    "author": "David Epstein",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8782615-M.jpg"
  },
  {
    "no": "book 62",
    "title": "The Checklist Manifesto",
    "author": "Atul Gawande",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8231866-M.jpg"
  },
  {
    "no": "book 63",
    "title": "Building a Second Brain",
    "author": "Tiago Forte",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12372866-M.jpg"
  },
  {
    "no": "book 64",
    "title": "Getting Things Done",
    "author": "David Allen",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/109288-M.jpg"
  },
  {
    "no": "book 65",
    "title": "Eat That Frog!",
    "author": "Brian Tracy",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/847534-M.jpg"
  },
  {
    "no": "book 66",
    "title": "The One Thing",
    "author": "Gary Keller",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10351762-M.jpg"
  },
  {
    "no": "book 67",
    "title": "Procrastination",
    "author": "Jane B. Burka",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7261122-M.jpg"
  },
  {
    "no": "book 68",
    "title": "Superlearning",
    "author": "Peter Hollins",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7084839-M.jpg"
  },
  {
    "no": "book 69",
    "title": "Learn Like an Einstein",
    "author": "Peter Hollins",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13891159-M.jpg"
  },
  {
    "no": "book 70",
    "title": "The First 20 Hours",
    "author": "Josh Kaufman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7288726-M.jpg"
  },
  {
    "no": "book 71",
    "title": "Ultralearning",
    "author": "Scott H. Young",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10156205-M.jpg"
  },
  {
    "no": "book 72",
    "title": "Mind Hacking",
    "author": "Sir John Hargrave",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8843804-M.jpg"
  },
  {
    "no": "book 73",
    "title": "The Joy of Movement",
    "author": "Kelly McGonigal",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9261636-M.jpg"
  },
  {
    "no": "book 74",
    "title": "Why We Sleep",
    "author": "Matthew Walker",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8814155-M.jpg"
  },
  {
    "no": "book 75",
    "title": "Breath",
    "author": "James Nestor",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10096454-M.jpg"
  },
  {
    "no": "book 76",
    "title": "Altered Traits",
    "author": "Daniel Goleman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9253925-M.jpg"
  },
  {
    "no": "book 77",
    "title": "Emotional Intelligence",
    "author": "Daniel Goleman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/1359485-M.jpg"
  },
  {
    "no": "book 78",
    "title": "Social Intelligence",
    "author": "Daniel Goleman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/374152-M.jpg"
  },
  {
    "no": "book 79",
    "title": "Incognito",
    "author": "David Eagleman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7891426-M.jpg"
  },
  {
    "no": "book 80",
    "title": "The Brain",
    "author": "David Eagleman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9576564-M.jpg"
  },
  {
    "no": "book 81",
    "title": "Livewired",
    "author": "David Eagleman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10201407-M.jpg"
  },
  {
    "no": "book 82",
    "title": "Behave",
    "author": "Robert M. Sapolsky",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8814831-M.jpg"
  },
  {
    "no": "book 83",
    "title": "Super Thinking",
    "author": "Gabriel Weinberg",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10153705-M.jpg"
  },
  {
    "no": "book 84",
    "title": "The Great Mental Models",
    "author": "Shane Parrish",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9778922-M.jpg"
  },
  {
    "no": "book 85",
    "title": "Thinking in Bets",
    "author": "Annie Duke",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8792782-M.jpg"
  },
  {
    "no": "book 86",
    "title": "Noise",
    "author": "Daniel Kahneman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10981966-M.jpg"
  },
  {
    "no": "book 87",
    "title": "Black Box Thinking",
    "author": "Matthew Syed",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/11349464-M.jpg"
  },
  {
    "no": "book 88",
    "title": "The Art of Thinking Clearly",
    "author": "Rolf Dobelli",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8270423-M.jpg"
  },
  {
    "no": "book 89",
    "title": "A Rulebook for Arguments",
    "author": "Anthony Weston",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/662363-M.jpg"
  },
  {
    "no": "book 90",
    "title": "Intuition Pumps and Other Tools for Thinking",
    "author": "Daniel C. Dennett",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7277286-M.jpg"
  },
  {
    "no": "book 91",
    "title": "The Mind's I",
    "author": "Douglas R. Hofstadter",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/298658-M.jpg"
  },
  {
    "no": "book 92",
    "title": "Gödel, Escher, Bach",
    "author": "Douglas R. Hofstadter",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/14368453-M.jpg"
  },
  {
    "no": "book 93",
    "title": "How to Read a Book",
    "author": "Mortimer J. Adler",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/405381-M.jpg"
  },
  {
    "no": "book 94",
    "title": "The Memory Book",
    "author": "Harry Lorayne",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/4996607-M.jpg"
  },
  {
    "no": "book 95",
    "title": "Remember It!",
    "author": "Nelson Dellis",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/11298531-M.jpg"
  },
  {
    "no": "book 96",
    "title": "Fluent Forever",
    "author": "Gabriel Wyner",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9413708-M.jpg"
  },
  {
    "no": "book 97",
    "title": "Words Can Change Your Brain",
    "author": "Andrew Newberg",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12938610-M.jpg"
  },
  {
    "no": "book 98",
    "title": "The Memory Illusion",
    "author": "Julia Shaw",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10490161-M.jpg"
  },
  {
    "no": "book 99",
    "title": "The Invisible Gorilla",
    "author": "Christopher Chabris",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8665878-M.jpg"
  },
  {
    "no": "book 100",
    "title": "You Are Not So Smart",
    "author": "David McRaney",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7381653-M.jpg"
  },
  {
    "no": "book 101",
    "title": "Hooked",
    "author": "Nir Eyal",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12511799-M.jpg"
  },
  {
    "no": "book 102",
    "title": "Peak Mind: Find Your Focus, Own Your Attention, Invest 12 Minutes a Day",
    "author": "Amishi P. Jha",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/11576434-M.jpg"
  },
  {
    "no": "book 103",
    "title": "The Extended Mind: The Power of Thinking Outside the Brain",
    "author": "Annie Murphy Paul",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12104740-M.jpg"
  },
  {
    "no": "book 104",
    "title": "Focusing",
    "author": "Eugene T. Gendlin",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10026941-M.jpg"
  },
  {
    "no": "book 105",
    "title": "Keep Your Brain Alive: 83 Neurobic Exercises to Help Prevent Memory Loss",
    "author": "Lawrence C. Katz & Manning Rubin",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/11456785-M.jpg"
  },
  {
    "no": "book 106",
    "title": "Brain Food: The Surprising Science of Eating for Cognitive Power",
    "author": "Lisa Mosconi",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13521833-M.jpg"
  },
  {
    "no": "book 107",
    "title": "Smart Thinking: Three Essential Keys to Solve Problems, Innovate, and Get Things Done",
    "author": "Art Markman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/isbn/9780399158643-M.jpg"
  },
  {
    "no": "book 108",
    "title": "Finish What You Start: The Art of Following Through, Taking Action, Executing, & Self-Discipline",
    "author": "Peter Hollins",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10531822-M.jpg"
  },
  {
    "no": "book 109",
    "title": "10-Minute Focus: 25 Small Habits to Master Your Attention",
    "author": "Damon Zahariades",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10521194-M.jpg"
  },
  {
    "no": "book 110",
    "title": "Fast Focus: A Quick-Start Guide To Mastering Your Attention",
    "author": "Damon Zahariades",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10520407-M.jpg"
  },
  {
    "no": "book 111",
    "title": "The User's Guide to the Brain: Perception, Attention, and the Four Theaters of the Brain",
    "author": "John J. Ratey",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/228276-M.jpg"
  },
  {
    "no": "book 112",
    "title": "Use Your Head: How to Unleash the Power of Your Mind",
    "author": "Tony Buzan",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/375204-M.jpg"
  },
  {
    "no": "book 113",
    "title": "The Brain That Changes Its Habits",
    "author": "Jeffrey M. Schwartz",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9825397-M.jpg"
  },
  {
    "no": "book 114",
    "title": "The Focus Zone: How to Beat Procrastination and Major Distractions",
    "author": "Lucy Jo Palladino",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/760118-M.jpg"
  },
  {
    "no": "book 115",
    "title": "Super Brain: Unleashing the Explosive Power of Your Mind",
    "author": "Deepak Chopra & Rudolph E. Tanzi",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8780870-M.jpg"
  },
  {
    "no": "book 116",
    "title": "Brain Wash: Detox Your Mind for Clearer Thinking, Deeper Relationships, and Lasting Happiness",
    "author": "David Perlmutter & Austin Perlmutter",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9264534-M.jpg"
  },
  {
    "no": "book 117",
    "title": "The SharpBrains Guide to Brain Fitness: How to Optimize Brain Health and Performance",
    "author": "Alvaro Fernandez & Elkhonon Goldberg",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12446457-M.jpg"
  },
  {
    "no": "book 118",
    "title": "High Performance Habits: How Extraordinary People Become That Way",
    "author": "Brendon Burchard",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/12385574-M.jpg"
  },
  {
    "no": "book 119",
    "title": "The Focus Effect: Change Your Habits, Change Your Life",
    "author": "Greg Wells",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9215229-M.jpg"
  },
  {
    "no": "book 120",
    "title": "Speed Reading: How to Read a Book a Day",
    "author": "Kam Knight",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10839827-M.jpg"
  },
  {
    "no": "book 121",
    "title": "Memory Improvement: How to Improve Your Memory in Just 30 Days",
    "author": "Kevin Horsley",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9946226-M.jpg"
  },
  {
    "no": "book 122",
    "title": "Brain Power: 64 Actionable Ideas to Open Your Mind",
    "author": "Michael J. Gelb",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/4356371-M.jpg"
  },
  {
    "no": "book 123",
    "title": "How to Develop a Super-Power Memory",
    "author": "Harry Lorayne",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/1640577-M.jpg"
  },
  {
    "no": "book 124",
    "title": "Biohack Your Brain: How to Boost Cognitive Health, Performance, and Power",
    "author": "Kristen Willeumier",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10551411-M.jpg"
  },
  {
    "no": "book 125",
    "title": "The Age-Proof Brain: New Science to Prevent Memory Loss and Keep Your Mind Sharp",
    "author": "Marc Milstein",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/11196262-M.jpg"
  },
  {
    "no": "book 126",
    "title": "Clear Thinking: Turning Ordinary Moments into Extraordinary Results",
    "author": "Shane Parrish",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/15208264-M.jpg"
  },
  {
    "no": "book 127",
    "title": "The Practice of Groundedness: A Transformative Path to Success",
    "author": "Brad Stulberg",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10961899-M.jpg"
  },
  {
    "no": "book 128",
    "title": "Make Your Brain Smarter: Increase Your Brain's Creativity, Energy, and Focus",
    "author": "Sandra Bond Chapman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7248784-M.jpg"
  },
  {
    "no": "book 129",
    "title": "The Productivity Project: Accomplishing More by Managing Your Time, Attention, and Energy",
    "author": "Chris Bailey",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8850807-M.jpg"
  },
  {
    "no": "book 130",
    "title": "How to Break Up with Your Phone: 30-Day Plan to Take Back Your Life",
    "author": "Catherine Price",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9269461-M.jpg"
  },
  {
    "no": "book 131",
    "title": "Bored and Brilliant: How Spacing Out Can Unlock Your Most Productive Self",
    "author": "Manoush Zomorodi",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10142388-M.jpg"
  },
  {
    "no": "book 132",
    "title": "Attention Pays: How to Drive Profitability, Productivity, and Accountability",
    "author": "Neen James",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8795096-M.jpg"
  },
  {
    "no": "book 133",
    "title": "Learn, Improve, Master: How to Develop Any Skill and Acquire Expertise",
    "author": "Nick Velasquez",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10247378-M.jpg"
  },
  {
    "no": "book 134",
    "title": "Hyper-Learning: How to Adapt to the Speed of Change",
    "author": "Edward D. Hess",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/14417990-M.jpg"
  },
  {
    "no": "book 135",
    "title": "Habits of a Happy Brain: Retrain Your Brain to Boost Your Neurochemicals",
    "author": "Loretta Graziano Breuning",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10209199-M.jpg"
  },
  {
    "no": "book 136",
    "title": "The Art of Memory",
    "author": "Frances A. Yates",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/450298-M.jpg"
  },
  {
    "no": "book 137",
    "title": "Master Your Mind Design Your Destiny",
    "author": "Adam Khoo",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8678542-M.jpg"
  },
  {
    "no": "book 138",
    "title": "Mental Toughness: How to Build Strong Mental Habits",
    "author": "Damon Zahariades",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/661199-M.jpg"
  },
  {
    "no": "book 139",
    "title": "Super Human Brain: Science-Backed Strategies to Sharpen Memory",
    "author": "Nicole M. Avena",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13058021-M.jpg"
  },
  {
    "no": "book 140",
    "title": "The Brain Always Wins",
    "author": "Chris Parker & Dr. John Sullivan",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7884139-M.jpg"
  },
  {
    "no": "book 141",
    "title": "Smart Change: Five Tools to Create New Habits",
    "author": "Art Markman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Habits & Discipline",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/9154494-M.jpg"
  },
  {
    "no": "book 142",
    "title": "Unkinking Your Brain",
    "author": "Stephen S. Ilardi",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/6444265-M.jpg"
  },
  {
    "no": "book 143",
    "title": "The Sweet Spot: How to Find Your Groove at Home and Work",
    "author": "Christine Carter",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7412966-M.jpg"
  },
  {
    "no": "book 144",
    "title": "Brain Switch",
    "author": "Craig Adams",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/7272162-M.jpg"
  },
  {
    "no": "book 145",
    "title": "Ageless Brain: High-Powered Brain Health",
    "author": "Rico Caveglia",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/isbn/9780735213616-M.jpg"
  },
  {
    "no": "book 146",
    "title": "Focus: The Ultimate Guide to Improving Your Focus",
    "author": "Ian Tuhovsky",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Focus & Concentration",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13232559-M.jpg"
  },
  {
    "no": "book 147",
    "title": "Fast Brain: How to Think Faster and Sharper",
    "author": "David J. Lieberman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Brain Science",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/10204949-M.jpg"
  },
  {
    "no": "book 148",
    "title": "Visual Intelligence: Sharpen Your Perception, Change Your Life",
    "author": "Amy E. Herman",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13224272-M.jpg"
  },
  {
    "no": "book 149",
    "title": "Mind Over Mind: The Surprising Science of Expectation",
    "author": "Chris Berdik",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Mindset & Logic",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/8695259-M.jpg"
  },
  {
    "no": "book 150",
    "title": "Visual Learning: Learn Faster, Remember More",
    "author": "Peter Hollins",
    "language": "HINDI",
    "status": "PENDING",
    "start_date": "",
    "end_date": "",
    "count_days": 0,
    "rating": "",
    "category": "Memory & Learning",
    "takeaway": "",
    "availability": "UNAVAILABLE",
    "cover_url": "https://covers.openlibrary.org/b/id/13230270-M.jpg"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DEFAULT_BOOKS };
}
